[backend]
# database   binary database faster queries 1 gpg and python (easier ha)
											# leave set
backend = "database"

# patterns to delete from db.
cachermPATTERNS = [
    '%caches%',
    '%.cache%',
    '%FontCache%',
    '%__pycache__%',
    '%C:\Users\{{user}}\AppData\Local\save-changesnew\flth%',
    '%\Microsoft\Windows\Recent\%'
]

# default for asymmetrical gpg auth for STATPST
                                                        # asks for paraphrase and caches for 15 minutes
                                                        # leave default
email = "john.doe@email.com"
name = "John e"

[logs]
# size to disable compression on pydbpst size
				# default 200
compLVL = 200								


					# default ERROR
					# DEBUG
logLEVEL = "ERROR"
userLOG = "errs.log"

[search]

# Focus drive for the app search and or sys profile 
drive = "C:\\"

# used for determining areas of multicore. the script will try to auto detect. If its set to SSD it will run multicore if over a certain file threshold
					# ""  default
					# SSD
					# HDD
driveTYPE=""

# Directories to exclude from the searches      Default Windows
# Applies to both pwrshell and wsl find
# prevent windows permission error. this applies to both powershell and wsl find command.
							# eg ["Windows", "Users\\{{user}}\\AppData\\Local\\Opera Software\\"]
EXCLDIRS = ["Windows", "$Recycle.Bin"]	

# Windows subsystem of linux - if it is unable to set it fall back to powershell.
				# default false 
wsl = false

						# How many old searches to save. These can be grabbed by `recentchanges search` and `recentchanges`
						# for comparisons in diff file
archivesrh = 5


# find file default extensions. added here as well as in qt which are stored in database 
extension = [
".txt", ".md", ".rtf", ".log", ".csv", ".tsv", ".json", ".xml", ".yaml", ".yml", ".ini",
".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".svg", ".heif", ".ico", ".raw",
".mp3", ".wav", ".aac", ".flac", ".ogg", ".m4a", ".wma", ".alac", ".opus",
".mp4", ".avi", ".mov", ".mkv", ".flv", ".webm", ".wmv", ".mpg", ".mpeg", ".3gp",
".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".odt", ".ods", ".odp", ".epub", ".mobi",
".zip", ".rar", ".7z", ".tar", ".gz", ".tar.gz", ".tgz", ".xz", ".bz2", ".iso",
".exe", ".bat", ".sh", ".app", ".jar", ".msi", ".apk", ".bin", ".run", ".vbs", ".wsf",
".html", ".htm", ".css", ".js", ".json", ".php", ".asp", ".jsp", ".xml", ".xhtml",
".sql", ".db", ".sqlite", ".db3", ".mdb", ".accdb", ".bak", ".frm", ".dbf",
".py", ".js", ".html", ".css", ".cpp", ".h", ".java", ".rb", ".go", ".rs", ".swift", ".php", ".pl",
".ttf", ".otf", ".woff", ".woff2", ".eot",
".vmdk", ".vdi", ".vhd", ".ova",
".dll", ".sys", ".drv", ".ini", ".cfg", ".bak",
".bak", ".backup", ".swp", ".tmp", ".~",
 ".iso", ".md5", ".sha1", ".torrent", ".dat"
]

# alternative to inotifywait for Windows. which for one hour would to look for new files where ctime > mtime in /. this is for downloads or copies with preserved metadata
# for Windows this uses a journal database with MFT data and USN updates. requires WSL
						# false - default. if false the files will still show up
xRC = false             	# true - With this setting can bypass 1 of 2 search loops and reduce process overhead as the search is already there effectively increasing the overall speed
							    

[compress]

# Find file feature compress. what program to use when making archive. 7zip is included by default
						# zipfile default python
						# winrar																	
						# 7zip
zipPROGRAM = "zipfile"
#zipPROGRAM = "7zip"													
#zipPROGRAM = "winrar"


# fallback incase cant find it in Path
# if the value "" is used the app will look in the registry for zipPROGRAM 7zip or winrar
# 7z will be used in app install if zipPROGRAM is not found
																#"" default		
zipPATH = ""																
#zipPATH = "C:\\Program Files\\7-Zip\\7z.exe"					
#zipPATH = "C:\\Program Files\\WinRAR\\WinRAR.exe"


# zipfile compression algorithm
							# 1-2 ZIP_STORED no compression
							# 3-4 ZIP_DEFLATED standard default
							# 5-7 ZIP_BZIP 
							# 8-9 ZIP_LZMA
zipcmode = 3
# zipfile compress level 0-9 default 9
ziplevel= 9

# 7zip compression level 9 ultra 0-9 ultra 7 maximum # default
_7zipcmode = 7

# Winrar compression level
							# default 3
							# 0-5
winrarcmode = 3

# remove paths or absolute. if there is a duplicate filename the duplicate will retain path                    
									# false - absolute default
									# true - no paths
strip = true


# path for archives from compress button search. Combobox output can be used to direct to AppData or Desktop.
# downloads is used if specified
												# "" default
												# ie "D:\\mydownloads\\"  , "C:\\users\\{{user}}\\Downloads"
downloads = ""									


[analytics]
							# display more verbose output
ANALYTICS = true
# provides more feedback
							# provides more feedback
							# total search time ect
							# we dont want too much output on the terminal just a slight bit more
							# others stats
ANALYTICSECT = true


# include search output in terminal as well ie scrolling terminal look
FEEDBACK = true


[display]

# gui start page 1 default 2 database
pageIDX = 1

# location to open explorer, cmd prompt or powershell from settings button
				# default ""
popPATH = ""														

#launch text editor?
# if using somethingelse specifying dspPATH is required
								# notepad  default 
									# "" "false" or false
									# notepad++
									# somethingelse
dspEDITOR = "notepad"


# specify absolute directory as a fallback incase cant find it in Path. Notepad is fine but needed for other editors. recommended
# if the value "" is used the app will check registry for dspEDITOR to see if its installed. notepad and notepad++ are checked anything
# else needs dspPATH specifcally
															# ""
															# "C:\\Program Files (x86)\\myeditor\\someexe.exe"
dspPATH = ""															
#dspPATH = "C:\\Program Files\\Notepad++\\notepad++.exe" 		


# color for main term display 
									# unix   default
									# wb  white on black
									# solar   solarize cyan
									# monochrome   for grey
									# modern
hudCOLOR = "unix"

								# default 12
hudSZE = 12

# see help - resources for more fonts
						# default Consolas									
						# Lucida	
						# Lucida Console
						# Courier New
						# Microsoft Sans Serif
						# serif
						# Monaco
						# Verdana
						# Times New Roman
						# Georgia
						# Tahoma
hudFNT = "Monaco"              	            



[diagnostics]

# compare file checksums for slight changes
						# slower useful if you want to check deeper level of stats
checkSUM = true


 # Include more info a file was changed but has the same checksum and filesize subtle edit  ie cache items or string was changed
						# also check for hash collisions
cdiag = true



# supress cache warnings on terminal from known browsers? Mozilla... ect
supbrw = true


# terminal and hardlink suppression. note regex
supbrwLIST = [
    'Mozilla\Firefox',
    'chromium-ungoogled',  # unconfirmed
    'Chrome\User Data',
    'Microsoft\Edge',
    'Opera Software',
    'C:\Users\{{user}}\AppData\Local\SomeFolder',
    'Default\Cache',   # spotify
    'Chrome\User Data\Default'
]


# ..      all cdiag output to terminal except critical events
suppress = false


# commandline use
# Create file doctrine. Runs post search operation that can only be done at this time as search is relevant
						# more overhead so recommend off unless one off. output /Downloads
						#
						# if it is run again and a file doctrine is still there it will not run the POSTOP and the script will set POSTOP to false to itself
POSTOP = false


# commandline use
# Scan  the sys profile. This is for commandline use. The profile is created automatically if proteusSHIELD is enabled. 
									# Once run once the script will set scanIDX to false.
scanIDX = false
# keep scanIDX on after scanning index
autoIDX = false

# commandline use
# Show symmetric differences in diff file for sys profile scan. For commandline use
showDIFF = false

		

[shield]
# commandline use
# take initial hash of key system files to put in database for system protection
									# builds a sys table in database of system files and is compared in hybrid analysis in addition to the logs table.
									# commandline use
proteusSHIELD = false	


# if false include all files found. otherwise only target windows executables. with this on there would be less results or a narrower profile.
exec = false				# false - default


# include symlinks in proteusEXTN and proteusPATH. symlinks are still mapped in dir cache for early exit in recursion and avoid tranversing in find downloads.
sym = true		# true - default


# files to include in the index. "" would means to include files with no extensions
# executable .exe, .msi, .bat, .com
proteusEXTN = [
	"", ".exe", ".msi", ".bat", ".com", ".dll", ".vbs", ".js", ".jse", ".ps1", ".reg", ".lnk",
	".vhd", ".vmdk", ".wsf",
	".ini", ".conf", ".cfg", ".sqlite", ".db"
]

# hash all in the following 
proteusPATH = [

]

# append to EXCLDIRS for profile builds. irrelevant folders
nogo = [
	'Users\{{user}}\AppData\Local\Temp',
	'Users\{{user}}\AppData\Local\Opera Software'
	
]

# no match file patterns removes noise.
filterout = [
	'Users\{{user}}\AppData\Roaming\Microsoft\Windows\Recent',
	'Users\{{user}}\AppData\Local\save-changesnew\gpg\gnupghome\random_seed'
]


[paths]
# file label prefix for searches output txt file			# default rntfiles
MODULENAME="rntfiles" 
