# database   binary database faster queries 1 gpg and python (easier ha)
[backend]
# patterns to delete from db on cache clear.
cachermPATTERNS = [
    'caches',
    '.cache',
    'FontCache',
    '__pycache__',
    'C:\Users\{{user}}\AppData\Local\save-changesnew\flth',
    '\Microsoft\Windows\Recent\'
]

# default for asymmetrical gpg auth for STATPST
                                        # asks for paraphrase and caches for 15 minutes
                                        # leave default
email = "john.doe@email.com"
name = "John e"

[logs]
# size to disable compression on pydbpst size
                # default 200
compLVL = 200


                    # default ERROR
                    # DEBUG
logLEVEL = "ERROR"
userLOG = "errs.log"

[search]
# Focus drive for the app search and or sys profile 
drive = "C:\\"

# used for determining areas of multicore. the script will try to auto detect. If its set to SSD it will run multicore if over a certain file threshold
                    # ""  default
                    # SSD
                    # HDD
driveTYPE=""

# Directories to exclude from the searches      Default Windows
# prevent windows permission error. this applies to both powershell and python scans.
                            # eg ["Windows"]
exclDIRS = ["Windows", "$Recycle.Bin", "Users\\{{user}}\\AppData\\Roaming\\Microsoft\\Windows\\Recent"]

# Use powershell. if false use alternative search Python instead of powershell.
                # default true 
pwrshell = true

# find file default extensions. added here as well as in qt which are stored in database 
extension = [
".txt", ".md", ".rtf", ".log", ".csv", ".tsv", ".json", ".xml", ".yaml", ".yml", ".ini",
".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".svg", ".heif", ".ico", ".raw",
".mp3", ".wav", ".aac", ".flac", ".ogg", ".m4a", ".wma", ".alac", ".opus",
".mp4", ".avi", ".mov", ".mkv", ".flv", ".webm", ".wmv", ".mpg", ".mpeg", ".3gp",
".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".odt", ".ods", ".odp", ".epub", ".mobi",
".zip", ".rar", ".7z", ".tar", ".gz", ".tar.gz", ".tgz", ".xz", ".bz2", ".iso",
".exe", ".bat", ".sh", ".app", ".jar", ".msi", ".apk", ".bin", ".run", ".vbs", ".wsf",
".html", ".htm", ".css", ".js", ".json", ".php", ".asp", ".jsp", ".xml", ".xhtml",
".sql", ".db", ".sqlite", ".db3", ".mdb", ".accdb", ".bak", ".frm", ".dbf",
".py", ".js", ".html", ".css", ".cpp", ".h", ".java", ".rb", ".go", ".rs", ".swift", ".php", ".pl",
".ttf", ".otf", ".woff", ".woff2", ".eot",
".vmdk", ".vdi", ".vhd", ".ova",
".dll", ".sys", ".drv", ".ini", ".cfg", ".bak",
".bak", ".backup", ".swp", ".tmp", ".~",
 ".iso", ".md5", ".sha1", ".torrent", ".dat"
]

# run watchdog for one hour to look for new files in basedir. if automation fails it doesnt effect the results as the purpose is
# to make file_creation_log and cache files over 1MB for ctimecache.gpg.
# reduces process overhead as larger created files or downloads the results are already there
xRC = false              # false - default. if false the files will still show up
                         # true

_time = 3600    # default xRC searches for 1 hour before closing. default is to clear file_creation_log

# Hours back to start file_creation_log.txt trim. then trim back to low water
high_water = 9

low_water = 6

# clear the log instead of high water if above minimum span hours
min_span = 0

                        # How many old searches to save. These can be grabbed by `recentchanges search` and `recentchanges`
                        # for comparisons in diff file
archivesrh = 5


[calculator]

                # regular
                # scientific
mode = "regular"

# decimal precision for scientific mode. working precision is always 30 digits higher.
                # 20 minimum
                # 150 max
decimals = 51

# leading zeros needed to use exponent notation
scientific_threshold = 6

                # default or ""
                # block
theme = "default"

# show computed expressions in hudt
history = false

# from 0 to target ceiling. 
randintMAX = 9999999

randintMIN = 0
                # default ERROR
                # DEBUG
logLEVEL="ERROR"


[compress]
# Find file feature compress. what program to use when making archive
                        # zipfile default (python)
                        # winrar
                        # 7zip
zipPROGRAM = "zipfile"

# fallback incase cant find it in Path
# if the value "" is used the app will look in the registry for zipPROGRAM 7zip or winrar
                        # "" default
                        # "C:\\Program Files\\WinRAR\\WinRAR.exe"
zipPATH = ""

# zipfile compression algorithm
                            # 1-2 ZIP_STORED no compression
                            # 3-4 ZIP_DEFLATED standard default
                            # 5-7 ZIP_BZIP 
                            # 8-9 ZIP_LZMA
zipcmode = 3

# zipfile compress level 0-9 default 9
ziplevel= 9

# 7zip compression level 9 ultra 0-9 ultra
                            # default 7. maximum
                            # 0-9. ultra
_7zipcmode = 7

# Winrar compression level
                            # default 3
                            # 0-5
winrarcmode = 3

# remove paths or absolute. if there is a duplicate filename the duplicate will retain path
                                    # false - absolute default
                                    # true - no paths
strip = true

# path for archives from compress button search. Combobox output can be used to direct to AppData or Desktop.
# downloads is used if specified
                                                # "" default
                                                # ie "D:\\mydownloads\\"  , "C:\\users\\{{user}}\\Downloads"
downloads = ""


[analytics]
# provides more feedback and display more verbose outputs
                            # total search time ect
                            # others stats
                            
analytics = true

# include search output in terminal as well ie scrolling terminal look
feedback = true


[display]
# gui start page 1 default 2 database
pageIDX = 1

# location to open explorer, cmd prompt or powershell from settings button
                # default ""
popPATH = ""

# launch text editor? if using somethingelse specifying dspPATH is required
                                # notepad  default 
                                # "" "false" or false
                                # notepad++
                                # somethingelse
dspEDITOR = "notepad"

# specify absolute directory as a fallback incase cant find it in Path. Notepad is in path but needed for other editors.
# if the value "" is used the app will check registry for dspEDITOR to see if its installed. notepad and notepad++ are checked anything else needs dspPATH specifcally
                                                            # ""
                                                            # "C:\\Program Files\\Notepad++\\notepad++.exe"
dspPATH = ""

# color for main term display 
                                    # unix   default
                                    # wb  white on black
                                    # solar   solarize cyan
                                    # monochrome   for grey
                                    # modern
hudCOLOR = "unix"

                                # default 12
hudSZE = 12

# see help - resources for more fonts default Consolas
                        # Lucida
                        # Lucida Console
                        # Courier New
                        # Microsoft Sans Serif
                        # serif
                        # Monaco
                        # Verdana
                        # Times New Roman
                        # Georgia
                        # Tahoma
hudFNT = "Monaco"


                    # false use 12 hour am pm
alarm_24hr = true

# color for alarm lcd display. default system theme
                                # ""
                                # redblack
                                # red
                                # blue
                                # black
alarmCOLOR = ""

# Place .mp3 or .wav in .\\Resources\\ and specify filename here
                                # "alarm.mp3"
alarm_soundFILE = ""

# specify filename when the alarm is set to play sound
                                # "alarmt.mp3"
alarm_set_soundFILE = ""

# Alarm sounds can be set from the custom button which copies the file to \\Resources\\ and sets the filename above accordingly


[diagnostics]
# compare file checksums for slight changes
                        # slower useful if you want to check deeper level of stats
checkSUM = true

 # Include more info a file was changed but has the same checksum and filesize subtle edit  ie cache items or string was changed
                        # also check for hash collisions
cdiag = true

# supress cache warnings on terminal from known browsers? Mozilla... ect
supbrw = true

# terminal suppression. note regex
supbrwLIST = [
    'Mozilla\Firefox',
    'chromium-ungoogled',  # unconfirmed
    'Chrome\User Data',
    'Microsoft\Edge',
    'Opera Software',
    'C:\Users\{{user}}\AppData\Local\SomeFolder',
    'Default\Cache',   # spotify
    'Chrome\User Data\Default'
]

# ..      all cdiag output to terminal except critical events
suppress = false

# commandline use
# Create file doctrine. Runs post search operation that can only be done at this time as search is relevant
# more overhead so recommend off unless one off. output Desktop
                        # if it is run again and a file doctrine is still there it will not run the POSTOP and the script will set POSTOP to false to itself
postop = false


[shield]
# take initial hash of key system files to put in database for system protection
                                    # builds a sys table in database of system files and is compared in hybrid analysis in addition to the logs table.
proteusSHIELD = false    
# end commandline use

# if false include all files found from proteusEXTN. otherwise only target windows executables. with this on there would be less results or a narrower profile.
exec = false                # false - default

# include symlinks in proteusEXTN and proteusPATH. symlinks are still mapped in dir cache for early exit in recursion
sym = true        # true - default

# files to include in the index. "" would means to include files with no extension
# executable .exe, .msi, .bat, .com
proteusEXTN = [
    "", ".exe", ".msi", ".bat", ".com", ".dll", ".vbs", ".js", ".jse", ".ps1", ".reg", ".lnk",
    ".vhd", ".vmdk", ".wsf",
    ".ini", ".conf", ".cfg", ".sqlite", ".db"
]

# hash all in the following 
proteusPATH = [

]

# append to EXCLDIRS for profile builds. irrelevant folders
#     'Users\{{user}}\AppData\Local\Temp',
nogo = [
    'Users\{{user}}\AppData\Local\Opera Software'
]

# no match file patterns removes noise
filterout = [
    'Users\{{user}}\AppData\Local\save-changesnew\gpg\gnupghome\random_seed'
]


[paths]
# file label prefix for searches output txt file. default rntfiles
moduleNAME="rntfiles" 
